artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/kamaleshkio/Text_Summarizer/raw/refs/heads/main/src/textSummarizer/textsummarizer_data/summarizer-data.zip
  local_data_file: data/ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
